name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run dist

      - name: Generate SHA256 (Linux)
        if: runner.os == 'Linux'
        run: |
          cd dist

          for file in *; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "$file.sha256"
            fi
          done

      - name: Generate SHA256 (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd dist

          Get-ChildItem -File | ForEach-Object {

            $hash = Get-FileHash `
              $_.FullName `
              -Algorithm SHA256

            "$($hash.Hash)  $($_.Name)" |
              Out-File "$($_.Name).sha256"

          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*